language: ruby
rvm:
  - 2.3.1
env:
#  - DB=sqlite
#  - DB=mysql
  - DB=postgresql
sudo: required

before_install: cp config/database.travis.yml config/database.yml

script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-arm7hf.tar.gz
  - tar -zxvf geckodriver-v0.11.1-arm7hf.tar.gz
  - sudo chmod +x geckodriver
  - sudo cp geckodriver /usr/bin

  - export RAILS_ENV=test
  - export CODECLIMATE_REPO_TOKEN=b38cccd7bf0953196140df84efaed5d3763d20aeb0eec0f4c368d16a8c643e37
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare  
  - bundle exec spec
